# Generated by Django 3.0 on 2022-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=64, verbose_name='订单号')),
                ('amount', models.FloatField(verbose_name='订单金额')),
            ],
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='评论内容')),
                ('score', models.FloatField(default=5, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='景点名称')),
                ('address', models.CharField(max_length=64, verbose_name='景点地址')),
            ],
        ),
        migrations.CreateModel(
            name='SightComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='评论内容')),
                ('score', models.FloatField(default=5, verbose_name='分数')),
            ],
        ),
    ]
